import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Provider } from "@/components/Providers";
import { Toast } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";

const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI-Peer-Tutor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.className} antialiased min-h-screen pt-16`}>
        <Provider>
          <Navbar/>
          {children}
          <Toaster/>
        </Provider>
      </body>
    </html>
  );
}
